---
- name: Setup WordPress Server
  hosts: your_server
  become: true

  tasks:
    - name: Update and upgrade system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install packages
      apt:
        name:
          - nginx
          - mysql-server
          - php-fpm
          - php-mysql
          - php-curl
          - php-gd
          - php-intl
          - php-mbstring
          - php-soap
          - php-xml
          - php-xmlrpc
          - php-zip
          - unzip
          - python3-certbot-nginx
          - rkhunter
          - fail2ban
        state: present

    - name: Update rkhunter database
      command: rkhunter --update
      changed_when: false

    - name: Check system files with rkhunter
      command: rkhunter --propupd
      changed_when: false

    - name: Setup daily job for rkhunter
      cron:
        name: rkhunter
        minute: 0
        hour: 3
        job: "/usr/bin/rkhunter --cronjob --update --quiet"
        user: root
        state: present

    - name: Allow Nginx Full and SSH through UFW
      ufw:
        rule: allow
        name: "{{ item }}"
      loop:
        - "Nginx Full"
        - "{{ ssh_port }}/tcp"

    - name: Change SSH port
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: '^#Port 22'
        line: 'Port {{ ssh_port }}'
      notify:
        - Restart SSH

    - name: Start and enable services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - mysql
        - fail2ban

    - name: Secure MySQL installation
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        update_password: always
      vars:
        mysql_root_password: your_mysql_root_password

    - name: Create WordPress database and user
      mysql_db:
        name: "{{ wordpress_db }}"
        state: present
      mysql_user:
        name: "{{ wordpress_user }}"
        password: "{{ wordpress_password }}"
        priv: "{{ wordpress_db }}.*:ALL"
        host: localhost
        state: present
      vars:
        wordpress_db: wordpress
        wordpress_user: wordpress_user
        wordpress_password: wordpress_password

    - name: Fetch and extract WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www/html
        remote_src: yes
        creates: /var/www/html/wordpress

    - name: Update WP config file
      template:
        src: wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php

    - name: Update nginx config file
      template:
        src: default.j2
        dest: /etc/nginx/sites-available/default

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted

    - name: Obtain SSL certificate
      command: certbot --nginx -d "{{ domain }}" -d "www.{{ domain }}" -n --agree-tos --email "{{ email }}" --redirect
      vars:
        domain: your_domain
        email: your_email

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted

    - name: Add bashrc
      copy:
        src: bashrc
        dest: /home/your-user/.bashrc
        owner: your-user
        group: your-user
        mode: '0644'
